version: "3"
services:
  blogson-mysql:
    container_name: "lessonplanjs-mysql"
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lessonplanjs
      MYSQL_USER: lessonplanjs
      MYSQL_PASSWORD: lessonplanjs
    volumes:
      - ./config.cnf:/etc/mysql/conf.d/custom.cnf
