export const LESSONS_TYPES = {
  REQUEST_LESSON: "lessons/REQUEST_LESSON",
  RECEIVE_LESSONS: "lessons/RECEIVE_LESSONS",
  RECEIVE_LESSON: "lessons/RECEIVE_LESSON",

  SET_ERRORS: "lessons/SET_LESSONS",
};
